export const currencies = 
[
  { code: 'AED', name: 'UAE Dirham', flag: '🇦🇪', locale: 'ar-AE' },
  { code: 'AUD', name: 'Australian Dollar', flag: '🇦🇺', locale: 'en-AU' },
  { code: 'BRL', name: 'Brazilian Real', flag: '🇧🇷', locale: 'pt-BR' },
  { code: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦', locale: 'en-CA' },
  { code: 'CHF', name: 'Swiss Franc', flag: '🇨🇭', locale: 'de-CH' },
  { code: 'CNY', name: 'Chinese Yuan', flag: '🇨🇳', locale: 'zh-CN' },
  { code: 'EGP', name: 'Egyptian Pound', flag: '🇪🇬', locale: 'ar-EG' },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺', locale: 'de-DE' },
  { code: 'GBP', name: 'British Pound', flag: '🇬🇧', locale: 'en-GB' },
  { code: 'HKD', name: 'Hong Kong Dollar', flag: '🇭🇰', locale: 'zh-HK' },
  { code: 'IDR', name: 'Indonesian Rupiah', flag: '🇮🇩', locale: 'id-ID' },
  { code: 'INR', name: 'Indian Rupee', flag: '🇮🇳', locale: 'en-IN' },
  { code: 'JPY', name: 'Japanese Yen', flag: '🇯🇵', locale: 'ja-JP' },
  { code: 'KRW', name: 'South Korean Won', flag: '🇰🇷', locale: 'ko-KR' },
  { code: 'MXN', name: 'Mexican Peso', flag: '🇲🇽', locale: 'es-MX' },
  { code: 'MYR', name: 'Malaysian Ringgit', flag: '🇲🇾', locale: 'ms-MY' },
  { code: 'NOK', name: 'Norwegian Krone', flag: '🇳🇴', locale: 'nb-NO' },
  { code: 'NZD', name: 'New Zealand Dollar', flag: '🇳🇿', locale: 'en-NZ' },
  { code: 'PHP', name: 'Philippine Peso', flag: '🇵🇭', locale: 'fil-PH' },
  { code: 'PKR', name: 'Pakistani Rupee', flag: '🇵🇰', locale: 'ur-PK' },
  { code: 'RUB', name: 'Russian Ruble', flag: '🇷🇺', locale: 'ru-RU' },
  { code: 'SAR', name: 'Saudi Riyal', flag: '🇸🇦', locale: 'ar-SA' },
  { code: 'SEK', name: 'Swedish Krona', flag: '🇸🇪', locale: 'sv-SE' },
  { code: 'SGD', name: 'Singapore Dollar', flag: '🇸🇬', locale: 'en-SG' },
  { code: 'THB', name: 'Thai Baht', flag: '🇹🇭', locale: 'th-TH' },
  { code: 'TRY', name: 'Turkish Lira', flag: '🇹🇷', locale: 'tr-TR' },
  { code: 'USD', name: 'US Dollar', flag: '🇺🇸', locale: 'en-US' },
  { code: 'VND', name: 'Vietnamese Dong', flag: '🇻🇳', locale: 'vi-VN' },
  { code: 'ZAR', name: 'South African Rand', flag: '🇿🇦', locale: 'en-ZA' }
]